config/routes.rb
Rails.application.routes.draw do
  scope '/:locale', locale: /en|de/ do
    resources :books do
      resources :chapters, except: %i(show), shallow: true
      resources :media, only: %i(index)
    end
    resources :users, except: %i(show)
    resources :media
    resources :newsletter_subscriptions, only: %i(create index)
  end
  root 'media#index', locale: 'en'
end

app/models/user.rb
class User < ActiveRecord::Base
  include Clearance::User
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  def index
    @users = User.all
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to users_path, notice: I18n.t('shared.created', resource: User.model_name.human)
    else
      render :new
    end
  end

  # PATCH/PUT /users/1
  def update
    if @user.update(user_params)
      redirect_to users_path, notice: I18n.t('shared.updated', resource: User.model_name.human)
    else
      render :edit
    end
  end

  # DELETE /users/1
  def destroy
    @user.destroy
    redirect_to users_path, notice: I18n.t('shared.destroyed', resource: User.model_name.human)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def user_params
      params.require(:user).permit(:email, :password)
    end
end

app/views/users/_form.html.erb
<%= simple_form_for(@user) do |f| %>
  <%= f.input :email %>
  <%= f.input :password %>

  <div class="actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1><%= t('shared.edit', resource: User.model_name.human ) %></h1>

<%= render 'form' %>

<%= link_to t('shared.back'), users_path %>

app/views/users/index.html.erb
<h1><%= User.model_name.human count: 2 %></h1>

<table>
  <thead>
    <tr>
      <th><%= User.human_attribute_name :email %></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td class="actions">
          <%= link_to t('shared.edit'), edit_user_path(user) %>
          <%= link_to t('shared.destroy'), user, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>

  <tfoot>
    <tr>
      <td colspan="2">
        <%= link_to t('shared.new', resource: User.model_name.human), new_user_path %>
      </td>
    </tr>
  </tfoot>
</table>

app/views/users/new.html.erb
<h1><%= t('shared.new', resource: User.model_name.human ) %></h1>

<%= render 'form' %>

<%= link_to t('shared.back'), users_path %>