config/routes.rb
Rails.application.routes.draw do
  scope '/:locale', locale: /en|de/ do
    resources :books do
      resources :chapters, except: %i(show), shallow: true
      resources :media, only: %i(index)
    end
    resources :users, except: %i(show)
    resources :media
    resources :newsletter_subscriptions, only: %i(create index)
  end
  root 'media#index', locale: 'en'
end

app/models/book.rb
class Book < ActiveRecord::Base
  translates :title, :description
  globalize_accessors

  dragonfly_accessor :image

  has_many :chapters
  has_many :media, through: :chapters

  validates :title_de, :title_en, presence: true
  validates :author, presence: true
  validates :description_de, :description_en, presence: true
  validates :image, presence: true

  def to_s
    title
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]
  skip_before_action :require_login, only: :index
  before_action :require_login, only: :index, unless: ->(controller) { controller.request.format.json? }

  # GET /books
  def index
    @books = Book.all

    if params[:changed_since]
      @books = @books.where('updated_at >= ?', params[:changed_since])
    end

    respond_to do |format|
      format.html {}
      format.json { render json: @books }
    end
  end

  # GET /books/1
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  def create
    @book = Book.new(book_params)

    if @book.save
      redirect_to @book, notice: I18n.t('shared.created', resource: Book.model_name.human)
    else
      render :new
    end
  end

  # PATCH/PUT /books/1
  def update
    if @book.update(book_params)
      redirect_to @book, notice: I18n.t('shared.updated', resource: Book.model_name.human)
    else
      render :edit
    end
  end

  # DELETE /books/1
  def destroy
    @book.destroy
    redirect_to books_url, notice: I18n.t('shared.destroyed', resource: Book.model_name.human)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def book_params
      params.require(:book).permit(:title_en, :title_de, :author, :description_en, :description_de, :image)
    end
end

app/views/books/_form.html.erb
<%= simple_form_for(@book) do |f| %>
  <%= f.input :title_de %>
  <%= f.input :title_en %>
  <%= f.input :author %>
  <%= f.input :description_de %>
  <%= f.input :description_en %>
  <%= f.input :image, as: :file %>

  <div class="actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1><%= t('shared.edit', resource: Book.model_name.human ) %></h1>

<%= render 'form' %>

<%= link_to t('shared.back'), books_path %>

app/views/books/index.html.erb
<h1><%= Book.model_name.human count: 2 %></h1>

<table>
  <thead>
    <tr>
      <th><%= Book.human_attribute_name :title %></th>
      <th><%= Book.human_attribute_name :author %></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.author %></td>
        <td class="actions">
          <%= link_to t('shared.show'), book %>
          <%= link_to t('shared.edit'), edit_book_path(book) %>
          <%= link_to t('shared.destroy'), book, method: :delete %>
        </td>
      </tr>
    <% end %>
  </tbody>

  <tfoot>
    <tr>
      <td colspan="3">
        <%= link_to t('shared.new', resource: Book.model_name.human), new_book_path %>
      </td>
    </tr>
  </tfoot>
</table>

app/views/books/new.html.erb
<h1><%= t('shared.new', resource: Book.model_name.human ) %></h1>

<%= render 'form' %>

<%= link_to t('shared.back'), books_path %>

app/views/books/show.html.erb
<h1>
  <%= @book.title %>
  <small><%= @book.author %></small>
</h1>

<%= image_tag @book.image.remote_url %>

<%= @book.description %>


<h2><%= Chapter.model_name.human count: 2 %></h2>
<%= render 'chapters/collection', book: @book, chapters: @book.chapters %>

<%= link_to t('shared.edit'), edit_book_path(@book) %> |
<%= link_to t('shared.back'), books_path %>