config/routes.rb
Rails.application.routes.draw do
  scope '/:locale', locale: /en|de/ do
    resources :books do
      resources :chapters, except: %i(show), shallow: true
      resources :media, only: %i(index)
    end
    resources :users, except: %i(show)
    resources :media
    resources :newsletter_subscriptions, only: %i(create index)
  end
  root 'media#index', locale: 'en'
end

app/controllers/media_controller.rb
class MediaController < ApplicationController
  before_action :set_medium, only: [:show, :edit, :update, :destroy]
  before_action :set_book, only: %i(index)
  skip_before_action :require_login, only: :show
  layout false, only: :show

  # GET /media
  def index
    @media = if @book
               @book.media
             else
               Medium.all
             end

    if params[:changed_since]
      @media = @media.where('media.updated_at >= ?', params[:changed_since])
    end

    respond_to do |format|
      format.html {}
      format.json { render json: @media }
    end
  end

  # GET /media/1
  def show
    respond_to do |format|
      format.html {}
      format.json { render json: @medium }
    end
  end

  # GET /media/new
  def new
    @medium = medium_class.new
  end

  # GET /media/1/edit
  def edit
  end

  # POST /media
  def create
    @medium = medium_class.new(medium_params)

    if @medium.save
      redirect_to media_url, notice: I18n.t('shared.created', resource: Medium.model_name.human)
    else
      render :new
    end
  end

  # PATCH/PUT /media/1
  def update
    if @medium.update(medium_params)
      redirect_to media_url, notice: I18n.t('shared.updated', resource: Medium.model_name.human)
    else
      render :edit
    end
  end

  # DELETE /media/1
  def destroy
    @medium.destroy
    redirect_to media_url, notice: I18n.t('shared.destroyed', resource: Medium.model_name.human)
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_medium
    @medium = Medium.find(params[:id])
  end

  def set_book
    @book = Book.find(params[:book_id]) if params[:book_id]
  end

  # Only allow a trusted parameter "white list" through.
  def medium_params
    params.require(:medium).permit(
      :chapter_id,
      :type,
      :title_de,
      :title_en,
      :teaser_de,
      :teaser_en,
      :thumbnail,
      :file,
      :movie1,
      :movie2,
      :description1_de,
      :description1_en,
      :description2_de,
      :description2_en,
    )
  end

  def medium_class
    if valid_type_given?
      @medium = params[:type].constantize
    else
      @medium = Medium
    end
  end

  def valid_type_given?
    %w(Movie TwoMoviesAndText).include? params[:type]
  end
end

app/views/media/_form.html.erb
<%= simple_form_for(@medium, as: :medium, url: (@medium.persisted? ? medium_path(@medium) : media_path)) do |f| %>
  <% unless @medium.persisted? %>
    <%= f.input :type, collection: [Movie, TwoMoviesAndText] %>
  <% end %>

  <% unless @medium.class == Medium %>
    <fieldset>
      <legend><%= t('.general') %></legend>
      <%= f.association :chapter, label_method: :to_s %>
      <%= f.input :title_de %>
      <%= f.input :title_en %>
      <%= f.input :teaser_de %>
      <%= f.input :teaser_en %>
      <div class="one-line">
        <div>
          <%= f.input :thumbnail, as: :file %>
        </div>
        <div>
          <%= image_tag @medium.thumbnail.thumb('400x200#').url if @medium.thumbnail_stored? %>
        </div>
      </div>
    </fieldset>

    <%= render "form.#{@medium.class.to_s.underscore}", f: f %>

    <div class="actions">
      <%= f.button :submit %>
    </div>
  <% end %>
<% end %>

app/views/media/_form.movie.html.erb
<fieldset id="movie">
  <legend><%= t('.details') %></legend>
  <%= f.input :file, as: :file %>
</fieldset>

app/views/media/_form.two_movies_and_text.html.erb
<fieldset id="two_movies_and_text">
  <legend><%= t('.details') %></legend>
  <%= f.input :description1_de, as: :text %>
  <%= f.input :description1_en, as: :text %>
  <%= f.input :movie1, as: :file %>
  <%= f.input :description2_de, as: :text %>
  <%= f.input :description2_en, as: :text %>
  <%= f.input :movie2, as: :file %>
</fieldset>

app/views/media/_movie.html.erb
<video width="100%" height="auto" controls autoplay poster="<%= @medium.thumbnail.remote_url %>">
  <source src="<%= @medium.file.remote_url %>" type="video/mp4">
  Your browser does not support the video tag.
</video>

app/views/media/_two_movies_and_text.html.erb
<video width="100%" height="auto" controls autoplay poster="<%= @medium.thumbnail.remote_url %>">
  <source src="<%= @medium.movie1.remote_url %>" type="video/mp4">
  Your browser does not support the video tag.
</video>

<video width="100%" height="auto" controls autoplay poster="<%= @medium.thumbnail.remote_url %>">
  <source src="<%= @medium.movie2.remote_url %>" type="video/mp4">
  Your browser does not support the video tag.
</video>

app/views/media/edit.html.erb
<h1><%= t('shared.edit', resource: Medium.model_name.human ) %></h1>

<%= render 'form' %>

<%= link_to t('shared.show'), medium_path(@medium) %> |
<%= link_to t('shared.back'), media_path %>

app/views/media/index.html.erb
<h1><%= Medium.model_name.human count: 2 %></h1>

<table>
  <thead>
    <tr>
      <th><%= Medium.human_attribute_name :type %></th>
      <th><%= Medium.human_attribute_name :title %></th>
      <th><%= Medium.human_attribute_name :teaser %></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @media.each do |medium| %>
      <tr>
        <td><%= medium.type %></td>
        <td><%= medium.title %></td>
        <td><%= medium.teaser %></td>
        <td class="actions">
          <%= link_to t('shared.show'), medium_path(medium) %>
          <%= link_to t('shared.edit'), edit_medium_path(medium) %>
          <%= link_to t('shared.destroy'), medium_path(medium), method: :delete %>
        </td>
      </tr>
    <% end %>
  </tbody>

  <tfoot>
    <tr>
      <td colspan="4">
        <%= link_to t('shared.new', resource: Medium.model_name.human), new_medium_path %>
      </td>
    </tr>
  </tfoot>
</table>

app/views/media/new.html.erb
<h1><%= t('shared.new', resource: Medium.model_name.human ) %></h1>

<%= render 'form' %>

<%= link_to t('shared.back'), media_path %>

app/views/media/show.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Esther - Mit Gott die Welt auf den Kopf stellen</title>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_link_tag 'media_show/bootstrap.min', media: 'all' %>
    <%= stylesheet_link_tag 'media_show/layout', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>

    <!-- Custom Fonts -->
    <link href="http://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
      <![endif]-->
  </head>
  <body>

    <% if signed_in? %>

      <nav>
        <div class="wrapper">
          <%= link_to Book.model_name.human(count: 2), books_path %>
          <%= link_to Medium.model_name.human(count: 2), media_path %>
          <%= link_to User.model_name.human(count: 2), users_path %>
          <%= link_to NewsletterSubscription.model_name.human(count: 2), newsletter_subscriptions_path %>
        </div>
      </nav>

      <section id="tools">
        <div class="container">
          <div class="row">
            <div class="col-lg-12 text-center">

              <%= link_to t('shared.edit'), edit_medium_path(@medium) %> |
              <%= link_to t('shared.back'), media_path %>

            </div>
          </div>
        </div>
      </section>
    <% end %>

    <header id="top" class="header">
      <div class="text-vertical-center">
        <%= image_tag 'esther.png' %>
      </div>
    </header>

    <section id="about" class="about">

      <div class="container">
        <div class="row">
          <div class="col-lg-12 text-center">
            <h1><%= @medium.title %></h1>
            <p class="lead"></p>

            <%= render @medium.class.to_s.underscore %>
          </div>
        </div>
        <!-- /.row -->
      </div>
      <!-- /.container -->

    </section>

    <footer>
      <div class="container">
        <div class="row">
          <div class="col-lg-10 col-lg-offset-1 text-center">
            <hr class="small">
            <p class="text-copy">&copy; 2016 <a href="https://www.icf.church/">ICF Church</a></p>
          </div>
        </div>
      </div>
    </footer>

  </body>

</html>