config/routes.rb
Rails.application.routes.draw do
  scope '/:locale', locale: /en|de/ do
    resources :books do
      resources :chapters, except: %i(show), shallow: true
      resources :media, only: %i(index)
    end
    resources :users, except: %i(show)
    resources :media
    resources :newsletter_subscriptions, only: %i(create index)
  end
  root 'media#index', locale: 'en'
end

app/models/chapter.rb
class Chapter < ActiveRecord::Base
  belongs_to :book

  validates :number, presence: true
  validates :title_de, :title_en, presence: true
  validates :book, presence: true

  has_many :media

  translates :title
  globalize_accessors

  default_scope -> { order('chapters.number ASC') }

  def to_s
    "#{book.to_s}: #{number}. #{title}"
  end
end

app/controllers/chapters_controller.rb
class ChaptersController < ApplicationController
  before_action :set_chapter, only: [:show, :edit, :update, :destroy]
  before_action :set_book, only: [:index, :new, :create]
  skip_before_action :require_login, only: :index
  before_action :require_login, only: :index, unless: ->(controller) { controller.request.format.json? }

  # GET /chapters
  def index
    @chapters = @book.chapters

    if params[:changed_since]
      @chapters = @chapters.where('chapters.updated_at >= ?', params[:changed_since])
    end

    render json: @chapters
  end

  # GET /chapters/1
  def show
  end

  # GET /chapters/new
  def new
    @chapter = @book.chapters.new
  end

  # GET /chapters/1/edit
  def edit
  end

  # POST /chapters
  def create
    @chapter = @book.chapters.new(chapter_params)

    if @chapter.save
      redirect_to @book, notice: I18n.t('shared.created', resource: Chapter.model_name.human)
    else
      render :new
    end
  end

  # PATCH/PUT /chapters/1
  def update
    if @chapter.update(chapter_params)
      redirect_to @chapter.book, notice: I18n.t('shared.updated', resource: Chapter.model_name.human)
    else
      render :edit
    end
  end

  # DELETE /chapters/1
  def destroy
    @chapter.destroy
    redirect_to @chapter.book, notice: I18n.t('shared.destroyed', resource: Chapter.model_name.human)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chapter
      @chapter = Chapter.find(params[:id])
    end

    def set_book
      @book = Book.find(params[:book_id])
    end

    # Only allow a trusted parameter "white list" through.
    def chapter_params
      params.require(:chapter).permit(:title_de, :title_en, :number, :book_id)
    end
end

app/views/chapters/_collection.html.erb
<table>
  <thead>
    <tr>
      <th><%= Chapter.human_attribute_name :number %></th>
      <th><%= Chapter.human_attribute_name :title %></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% chapters.each do |chapter| %>
      <tr>
        <td><%= chapter.number %></td>
        <td><%= chapter.title %></td>
        <td class="actions">
          <%= link_to t('shared.edit'), edit_chapter_path(chapter) %>
          <%= link_to t('shared.destroy'), chapter, method: :delete %>
        </td>
      </tr>
    <% end %>
  </tbody>

  <tfoot>
    <tr>
      <td colspan="3">
        <%= link_to t('shared.new', resource: Chapter.model_name.human), new_book_chapter_path(book) %>
      </td>
    </tr>
  </tfoot>
</table>

app/views/chapters/_form.html.erb
<%= simple_form_for([@book, @chapter]) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title_de %>
    <%= f.input :title_en %>
    <%= f.input :number %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/chapters/edit.html.erb
<h1><%= t('shared.edit', resource: Chapter.model_name.human ) %></h1>

<%= render 'form' %>

<%= link_to t('shared.back'), @chapter.book %>

app/views/chapters/new.html.erb
<h1><%= t('shared.new', resource: Chapter.model_name.human ) %></h1>

<%= render 'form' %>

<%= link_to t('shared.back'), book_path(@book) %>

app/views/chapters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @chapter.title %>
</p>

<p>
  <strong>Number:</strong>
  <%= @chapter.number %>
</p>

<p>
  <strong>Book:</strong>
  <%= @chapter.book %>
</p>

<%= link_to 'Edit', edit_chapter_path(@chapter) %> |
<%= link_to 'Back', chapters_path %>